const categories = {
"01":"ALIMENTATION ET HEBERGEMENT",
"02":"TEXTILES",
"03":"FORMATION QUALIFICATION",
"04":"AFFRANCHISSEMENT, DOCUMENTATION ET PRODUITS DE L'EDITION",
"05":"ENVIRONNEMENT DU BUREAU ET MOBILIER",
"06":"SYSTEMES INFORMATIQUES ET TELECOMS",
"07":"PRESTATIONS JURIDIQUES",
"08":"ETUDES",
"09":"PREVENTION",
"10":"COMMUNICATION",
"11":"CULTURE ANIMATION DIVERTISSEMENT",
"12":"PROPRETE ET HYGIENE",
"13":"TRANSPORT",
"14":"MAINTENANCE BATIMENTS ET ESPACES PUBLICS",
"15":"CONSTRUCTION TRAVAUX RESEAUX",
"16":"ESPACES VERTS, CIMETIERE, ANIMALERIE",
"17":"SANITAIRE ET SOCIAL",
"18":"AUDIOVISUEL",
"19":"SECURITE PREVENTION ET POLICE MUNICIPALE"
};


